### ISSUE TITLE
Using BATS for unit tests?

### ISSUE THREAD

**Issue by mattock** [OpenVPN/easyrsa-unit-tests#8]
I've been involved in the [freight](https://github.com/freight-team/freight) project. Freight is a shell-based apt repo management software.

Freight uses a bash/shell unit test framework called [BATS](https://github.com/bats-core/bats-core). I'm just wondering if you guys have heard about it, or considered using it?

**Comment by ecrist** [comment]
Never heard about it.  This separate repo was created to uncouple the unit tests from the easy-rsa repo so that TravisCI could actually do something useful (a PR with bugs in the test script could never be fixed in TravisCI).  

We're not opposed to looking, and anything that makes our testing easier, the better.

**Comment by mattock** [comment]
Ok, just wanted to mention that. Don't know if BATS would make writing tests easier, but it might be worth a try at least.
